export default [
    'Kuriboh',
  'Magician of Black Chaos',
  'Celtic Guardian',
  'Jinzo',
  'Thousand-Eyes Restrict',
  'Harpy Lady',
  'Blue-Eyes Ultimate Dragon',
  'Relinquished',
  'Sangan',
  'Swords of Revealing Light',
  'Trap Hole',
  'Heavy Storm',
  'Mystical Space Typhoon',
  'Black Rose Dragon',
  'Elemental HERO Flame Wingman',
  'Neo-Spacian Grand Mole',
  'Red-Eyes Darkness Metal Dragon',
  'Number 39: Utopia',
  'Polymerization',
  'Graceful Charity',
];
