export default [
    'Dark Magician',
    'Blue-Eyes White Dragon',
    'Red-Eyes Black Dragon',
    'Summoned Skull',
    'Exodia the Forbidden One',
    'Obelisk the Tormentor',
    'Slifer the Sky Dragon',
    'The Winged Dragon of Ra',
    'Time Wizard',
    'Buster Blader',
    'Monster Reborn',
    'Mirror Force',
    'Pot of Greed',
    'Change of Heart',
    'Cyber Dragon',
    'Elemental HERO Neos',
    'Stardust Dragon',
    'Black Luster Soldier',
    'Dark Hole',
    'Raigeki',
];
